### ISSUE TITLE
Reference Error: primordials is not defined while running app

### ISSUE THREAD

**Issue by Bijayrauniyar** [OfficeDev/microsoft-teams-sample-auth-node#26]
$ gulp build
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/bijay/projects/optimum/microsoft-teams-sample-auth-node/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/bijay/projects/optimum/microsoft-teams-sample-auth-node/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/bijay/projects/optimum/microsoft-teams-sample-auth-node/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
error Command failed with exit code 1.

**Comment by lukedukeus** [comment]
This can be solved by using node 10.0.0
